# Generated by Django 6.0.3 on 2026-03-14 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(help_text='e.g. /users/:id', max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_endpoints', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'mock_endpoints',
                'ordering': ['path', 'method'],
                'unique_together': {('workspace', 'path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='MockResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=200)),
                ('status_code', models.IntegerField(default=200)),
                ('headers', models.JSONField(default=dict, help_text='Response headers as JSON object')),
                ('body', models.TextField(default='{}')),
                ('body_type', models.CharField(choices=[('json', 'JSON'), ('xml', 'XML'), ('text', 'Plain Text'), ('html', 'HTML')], default='json', max_length=20)),
                ('latency_ms', models.IntegerField(default=0, help_text='Fixed latency in ms')),
                ('latency_jitter_ms', models.IntegerField(default=0, help_text='Random jitter added to latency')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False, help_text='Returned when no rule matches')),
                ('priority', models.IntegerField(default=0, help_text='Higher = evaluated first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='endpoints.mockendpoint')),
            ],
            options={
                'db_table': 'mock_responses',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('body', 'Request Body'), ('query', 'Query Param'), ('header', 'Header'), ('path', 'Path Param')], max_length=20)),
                ('field', models.CharField(help_text='Field name / key', max_length=200)),
                ('operator', models.CharField(choices=[('eq', 'equals'), ('neq', 'not equals'), ('contains', 'contains'), ('starts_with', 'starts with'), ('gt', 'greater than'), ('lt', 'less than'), ('exists', 'exists'), ('not_exists', 'not exists')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='endpoints.mockresponse')),
            ],
            options={
                'db_table': 'response_rules',
            },
        ),
    ]
