# Generated by Django 6.0.3 on 2026-03-14 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(default=dict)),
                ('request_headers', models.JSONField(default=dict)),
                ('request_body', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='endpoints.mockendpoint')),
                ('matched_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='endpoints.mockresponse')),
            ],
            options={
                'db_table': 'request_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', '-created_at'], name='request_log_endpoin_c22cbd_idx'), models.Index(fields=['status_code'], name='request_log_status__5a9c0b_idx')],
            },
        ),
    ]
